### ISSUE TITLE
Attention Reuqired 

### ISSUE THREAD

**Issue by 2vikki** [googlecreativelab/giantemoji#1]
Error:Addon ofxAndroidMobileVision could not be found at C:\Users\Sunder\Downloads\giantemoji-master\giantemoji-master\gmojiAndroid........\addons\ofxAndroidMobileVision

i cloned/added required addons on to the app folder as well as on C drive users folder still its showing the same error.I am using android studio 2.2 RC how to clear this problem.Kindly clear this issue

**Comment by HalfdanJ** [comment]
Hi, sorry for being slow responding. 
Did you put the ofxAndroidMobileVision addon into the OF_ROOT/addons folder? Also did you use the special branch of openFrameworks for Android Studio? I looks like in the path that there might be a bug in openFrameworks on windows with the relative paths not being resolved correctly.

**Comment by itychange** [comment]
error: libs/openFrameworksCompiled/project/android/common-functions.gradle not found
you can help me?

**Comment by agnaramonboris** [comment]
@itychange hi ! You should clone or download openFrameworks toolkit, its depedencies and place it to the specified path ! For more details, read [https://github.com/googlecreativelab/giantemoji#dependencies](dependencies) section of README.md
