### ISSUE TITLE
OF_ROOT

### ISSUE THREAD

**Issue by theagilepadawan** [googlecreativelab/giantemoji#12]
Hi,

Sorry to bother you with such a rookie question but what does OF_ROOT means? 
And in this case, when I'm cloning the dependencies where shoud OF_ROOT/addons be?
When I'm trying to build it get: "Error:Addon ofxAndroidMobileVision could not be found at C:\Users\Michael\Downloads\giantemoji-master\gmojiAndroid\..\..\..\..\addons\ofxAndroidMobileVision"

Again, sorry. I just really want to test this :)

**Comment by theagilepadawan** [comment]
Think I sorted that one out, but now I'm getting:
 "Error:Illegal/unsupported escape sequence near index 5
.*C:\Users\Michael\Downloads\openFrameworks-gradle-experimental\addons\ofxFaceTracker2/libs/dlib/include/.+
     ^"

**Comment by Guiladg** [comment]
The same here. What can we do?

**Comment by Droidin** [comment]
Try build the project on other OSs, like ubuntu or macOS. In Windows, gradle may not handle windows paths correctly.
