### ISSUE TITLE
Gradle sync failed. Anyone know how to resolve this issue?

### ISSUE THREAD

**Issue by 0001vrn** [googlecreativelab/giantemoji#18]
Error:Illegal/unsupported escape sequence near index 5
.*C:\Users\Varun\Desktop\openFrameworks-gradle-experimental\apps\devApps\giantemoji-master\gmojiAndroid\..\..\..\..\addons\ofxFaceTracker2/libs/dlib/include/.+
     ^

**Comment by nijisakai** [comment]
Error:Illegal/unsupported escape sequence near index 5
.*C:\Users\hyinn\Documents\openFrameworks\apps\devApps\giantemoji-master\gmojiAndroid\..\..\..\..\addons\ofxFaceTracker2/libs/dlib/include/.+
     ^
exactly the same error

**Comment by puneetverma24** [comment]
me too facing the same issue. 
I found one solution "Try to build the project on other OSs, like Ubuntu or macOS. In Windows, gradle may not handle windows paths correctly".

Do you have any solution for windows? Where in the code you have written this 
"addons\ofxFaceTracker2/libs/dlib/include/.+" 
I want to try something to fix this.

**Comment by danzeeeman** [comment]
openFrameworks+Android on Windows is very temperamental.  OF only recently supported building for Android on Windows accidentally when we updated to the build process to use the gradle-experimental plugin.  

It appears that some of the wildcard characters used to recursively exclude items doesn't work on Windows.  If you want to solve the problem please experiment with changes in this section of the [common-functions.gradle](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworksCompiled/project/android/common-functions.gradle#L110) that handles excluding items from the build process or the[ addon_config.mk in ofxFaceTracker2](https://github.com/HalfdanJ/ofxFaceTracker2/blob/master/addon_config.mk).

**Comment by Jay670** [comment]
> me too facing the same issue.
> I found one solution "Try to build the project on other OSs, like Ubuntu or macOS. In Windows, gradle may not handle windows paths correctly".
> 
> Do you have any solution for windows? Where in the code you have written this
> "addons\ofxFaceTracker2/libs/dlib/include/.+"
> I want to try something to fix this.

Did you were able to fix the problem in windows? If yes, can you share what did you do to correct it?

**Comment by rahuljidgedev** [comment]
Me too have this problem. Do you guys able to find the solution to this?
