### ISSUE TITLE
Can't Get Running

### ISSUE THREAD

**Issue by brennick** [googlecreativelab/giantemoji#2]
I'm getting the following errors when trying to run on the Pixel C emulator

```
Error:error: /Users/connerb/Desktop/libs/openFrameworksCompiled/project/android/build/intermediates/binaries/debug/arm7/obj/armeabi-v7a/libopenFrameworksLib.a: no archive symbol table (run ranlib)
```

```
Error:Execution failed for task ':linkOFAndroidAppArmeabi-v7aDebugArm7SharedLibrary'.
> A build operation failed.
      Linker failed while linking libOFAndroidApp.so.
  See the complete log at: file:///Users/connerb/Desktop/giant%20emoji%20stuff/giantemoji/gmojiAndroid/build/tmp/linkOFAndroidAppArmeabi-v7aDebugArm7SharedLibrary/output.txt
```

As well 631 errors related to undefined references. Seems to me that its a linking error but can't figure out why the error is occuring.

I installed the branch of openFrameworks that was specified and have all the addons imported

**Comment by HalfdanJ** [comment]
Must be honest that I havent really tested the branch well against the emulator. It looks like it wont work since its missing builds for the correct build architecture in the emulator.

**Comment by brennick** [comment]
Alright, will try on an actual Android device and update later.

**Comment by brennick** [comment]
@HalfdanJ was this built using a Windows PC or Mac?

**Comment by HalfdanJ** [comment]
Mac, there might be some issues with the openFrameworks branch for android studio and windows..
