### ISSUE TITLE
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.

### ISSUE THREAD

**Issue by nijisakai** [googlecreativelab/giantemoji#20]
Information:Gradle tasks [:ofAndroidLib:generateDebugSources, :ofAndroidLib:generateDebugAndroidTestSources, :ofAndroidLib:mockableAndroidJar, :ofAndroidLib:prepareDebugUnitTestDependencies, :generateArm7DebugSources, :generateArm7DebugAndroidTestSources, :prepareArm7DebugUnitTestDependencies, :mockableAndroidJar, :ofxAndroidMobileVision:generateDebugSources, :ofxAndroidMobileVision:generateDebugAndroidTestSources, :ofxAndroidMobileVision:mockableAndroidJar, :ofxAndroidMobileVision:prepareDebugUnitTestDependencies]
Warning:Dependency org.json:json:20090211 is ignored for arm7Debug as it may be conflicting with the internal version provided by Android.
Warning:Dependency org.json:json:20090211 is ignored for arm7Release as it may be conflicting with the internal version provided by Android.
Warning:Dependency org.json:json:20090211 is ignored for x86Debug as it may be conflicting with the internal version provided by Android.
Warning:Dependency org.json:json:20090211 is ignored for x86Release as it may be conflicting with the internal version provided by Android.
/Users/chenhongyu/code/openFrameworks-master/apps/devApps/giantemoji/gmojiAndroid/build/intermediates/res/merged/arm7/debug/values-v21/values-v21.xml
Error:(13) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Inverse'.
Error:(15) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large.Inverse'.
Error:(21) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium.Inverse'.
Error:(28) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small.Inverse'.
Error:(207) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar'.
Error:(209) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ProgressBar.Horizontal'.
Error:(212) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:(222) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material'.
Error:(229) Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'.
Error:(174) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.AutoCompleteTextView'.
Error:(183) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.EditText'.
Error:(6) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body1'.
Error:(5) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Body2'.
Error:(7) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Caption'.
Error:(8) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display1'.
Error:(9) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display2'.
Error:(10) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display3'.
Error:(11) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Display4'.
Error:(12) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Headline'.
Error:(14) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Large'.
Error:(16) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:(18) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:(20) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Medium'.
Error:(22) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Menu'.
Error:(23) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.SearchResult.Subtitle'.
Error:(25) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.SearchResult.Title'.
Error:(27) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Small'.
Error:(29) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Subhead'.
Error:(30) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Title'.
Error:(31) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Menu'.
Error:(33) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:(35) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle.Inverse'.
Error:(37) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:(39) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title.Inverse'.
Error:(41) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Subtitle'.
Error:(43) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionMode.Title'.
Error:(45) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Large'.
Error:(47) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.PopupMenu.Small'.
Error:(49) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Button'.
Error:(50) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.TextView.SpinnerItem'.
Error:(51) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Subtitle'.
Error:(53) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.ActionBar.Title'.
Error:(163) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabText'.
Error:(165) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionBar.TabView'.
Error:(167) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton'.
Error:(169) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.CloseMode'.
Error:(172) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ActionButton.Overflow'.
Error:(175) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button'.
Error:(176) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Borderless'.
Error:(177) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Borderless.Colored'.
Error:(178) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Small'.
Error:(179) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ButtonBar'.
Error:(180) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.CompoundButton.CheckBox'.
Error:(181) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.CompoundButton.RadioButton'.
Error:(182) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.DropDownItem.Spinner'.
Error:(184) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:(186) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabText'.
Error:(188) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.ActionBar.TabView'.
Error:(190) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Light.PopupMenu'.
Error:(196) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListPopupWindow'.
Error:(198) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView'.
Error:(199) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.ListView.DropDown'.
Error:(201) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.PopupMenu'.
Error:(211) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.RatingBar'.
Error:(213) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner'.
Error:(218) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Spinner.Underlined'.
Error:(219) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.TextView.SpinnerItem'.
Error:(220) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Toolbar.Button.Navigation'.
/Users/chenhongyu/code/openFrameworks-master/apps/devApps/giantemoji/gmojiAndroid/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.1/res/values-v21/values-v21.xml
Error:(77, 5) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(77, 5) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(126, 5) No resource found that matches the given name: attr 'android:windowElevation'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(129, 5) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(178, 5) No resource found that matches the given name: attr 'android:windowElevation'.
Error:(212, 5) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:(223, 5) No resource found that matches the given name: attr 'android:overlapAnchor'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(258, 5) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorAccent'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorButtonNormal'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorControlActivated'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorControlHighlight'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorControlNormal'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorPrimary'.
Error:(268, 5) No resource found that matches the given name: attr 'android:colorPrimaryDark'.
Error:Execution failed for task ':processArm7DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/chenhongyu/Library/Android/sdk/build-tools/23.0.3/aapt'' finished with non-zero exit value 1
Information:BUILD FAILED
Information:Total time: 9.309 secs
Information:103 errors
Information:4 warnings
Information:See complete output in console

**Comment by danzeeeman** [comment]
please see the latest updates
