### ISSUE TITLE
[SOLVED]Failed to sync Gradle project

### ISSUE THREAD

**Issue by wingedpanther** [googlecreativelab/giantemoji#23]
How to fix [this ](https://i.imgur.com/HesDhMW.png)issue?. Using Android Studio 2.1.2 on Windows 10.

**Comment by wingedpanther** [comment]
Issue resolved -  [This ](https://stackoverflow.com/a/42654435/3682599)helped

**Comment by danzeeeman** [comment]
Upgrade to Android Studio 3.0

**Comment by danzeeeman** [comment]
Please close the issue
