### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by pamuditha** [googlecreativelab/giantemoji#28]
[FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':openFrameworksProject:createOpenFrameworksLibArmeabi-v7aDebugArm7StaticLibrary'.
> Could not find Static library archiver 'ar'. Searched in:
    - /home/user/Desktop/of/android-ndk-r10e/toolchains/llvm-3.6/prebuilt/linux-x86_64/bin
    - /home/user/Desktop/of/android-ndk-r10e/toolchains/llvm-3.6/prebuilt/linux-x86_64/bin
    - /home/user/Desktop/of/android-ndk-r10e/toolchains/llvm-3.6/prebuilt/linux-x86_64/bin
    - /home/user/Desktop/of/android-ndk-r10e/toolchains/llvm-3.6/prebuilt/linux-x86_64/bin

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.]

**Comment by HalfdanJ** [comment]
Try to update to the latest version of openFrameworks (0.10.0). A lot of work has now been done in fixing these errors.
