### ISSUE TITLE
project refresh failed 

### ISSUE THREAD

**Issue by Droidin** [googlecreativelab/giantemoji#4]
I follow the [instruction ](https://github.com/HalfdanJ/openFrameworks/blob/gradle-experimental/docs/android_studio.md) to build the project which download from this repo.
I also downloaded [openframeworks](https://github.com/halfdanj/openframeworks/tree/gradle-experimental) and installed dependicies. NDK version is r10e.
But eventually Android Studio 2.2 can't build this project successfully, and message view shown:
![image](https://cloud.githubusercontent.com/assets/16255157/19233244/e5f61be8-8f16-11e6-8c3d-1a4d5e900e20.png)
What can I do ? 
 this is the idea.log https://gist.github.com/Droidin/8045353c2c0cc4a8febb4314435a9c4e

**Comment by HalfdanJ** [comment]
It seems like there is a bug with the gradle setup for openFrameworks using Windows not handling windows paths correctly. Havent tested it on windows at all (on on macOS). I will try and find some time to install it on windows and see if I can find the bug, but not sure when I get time for it.

**Comment by Droidin** [comment]
Okay,I will try on macOS. And is anywhere I can get GiantEmoji APK file ? Because I can't find it on Android Experiments.
Thank you very much.

**Comment by Droidin** [comment]
I try to build this on Unbutu and show me this 
![image](https://cloud.githubusercontent.com/assets/16255157/19264364/0eba0582-8fd3-11e6-87a8-a306a633f0f0.png)

**Comment by Droidin** [comment]
Change NDK to r11 and copy “ar” from other  folder in toolchains mentioned  [here](https://github.com/openframeworks/openFrameworks/pull/5059) , then change the compileSdkVersion of  main module of project to 23 and make project. It will fail to do that. Now you need change compileSdkVersion to 19 or lower than 23 again and Build Apk will success.
All of those steps were completed on Unbutu

**Comment by Victoryczz** [comment]
@Droidin hey bro，sorry to borther， I've met this problem too on windows, have you solve this? 

![image](https://cloud.githubusercontent.com/assets/22150464/26200831/aa84ad92-3c02-11e7-9d82-99924ececa43.png)
Should I just update my Android NDK to r12b？

**Comment by Droidin** [comment]
@Victoryczz you should try on Unbutu or macOS. And I'm not sure to update NDK to r12b will solve the prolem. you can try PR#8, or use gradle-experimental:0.9.0 or 092  and  ndk r13b or r14b.
