### ISSUE TITLE
Error for project refresh failed

### ISSUE THREAD

**Issue by norippy-i** [googlecreativelab/giantemoji#5]
I tried to below environment. 

AndroidStudio:2.2.2.0 (OS is El Capitan)
NDK:r10e
And I already installed 4 addons 

But I couldn't get running.
I found below error in Gradle Sync.

Error:Attempt to read property 'manifest' from a write only view of model element 'android.sources.main' of type 'FunctionalSourceSet' given to rule main { ... } @ ../../openFrameworks/addons/ofxAndroid/ofAndroidLib/build.gradle line 10, column 9

What can I do? Please tell me some advise.

**Comment by miualinionut** [comment]
I have the same problem.
Can you please help us ?

**Comment by magdamiu** [comment]
Same issue here.
Please could someone tell us what's wrong and how can we solve the issue?
Thank you!

**Comment by norippy-i** [comment]
I solved this problem myself.
This problem is caused by sync gradle . When you click the "Sync Project with Gradle file", you can see the pop windows about changing gradle. First time I clicked "update".  It makes this problem.
You don't change gradle version!
