### ISSUE TITLE
Gradle sync failed: Could not read script '/Users/libs/openFrameworksCompiled/project/android/common-functions.gradle' as it does not exist.

### ISSUE THREAD

**Issue by chetan-yg** [googlecreativelab/giantemoji#6]
I am trying to load the project in Android Studio 2.2.2, But this error i am getting. Any solutions?

**Comment by jnikhilreddy** [comment]
same problem here? also tried to download common-functions.gradle lib
there is no common-functions.gradle in 
https://github.com/openframeworks/openFrameworks/tree/master/libs/openFrameworksCompiled/project/android
@Chetanyg fond any solution?

**Comment by jnikhilreddy** [comment]
Could you guys provide apk file or solution to this problem
@stewdio @alexanderchen @trippedout @HalfdanJ

**Comment by pulkitcs** [comment]
Hi, I am facing the same issue here as well. Could you please help/guide ?

**Comment by AmineI** [comment]
I had the issue as well. I deleted the project and redownloaded it and it's now fine, can you check ?

**Comment by HalfdanJ** [comment]
We are working on an update for the project and openFrameworks build.

**Comment by AmineI** [comment]
Good to know !
@pulkitcs The problem in that case was that the "ofroot" path in build.gradle is relative. By default it's 4 levels under the current folder. Depending on where you placed the folder, just edit your ofroot path.

**Comment by sexnine** [comment]
So how do you resolve this?  Or is this something the devs need to fix?
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117530-242693323_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by AmineI** [comment]
By fixing your build.gradle .
`def ofRoot(){ return '../../../../' }`
here you must set the relative path of the ofroot folder. It will differ between people etc depending on where you put the project.

**Comment by SmokingSlim** [comment]
Hi guys, found the ofroot path. Couldn't find common-functions.gradle tho in either OSX or Mobile Android Frameworks gits. Is it something custom that you guys built? Thanks.

**Comment by pineoc** [comment]
I have same issue!

**Comment by janithachanuka** [comment]
Having the same issue. Anyone figure out a solution?

**Comment by HalfdanJ** [comment]
Please try the pr #8 and the version of openframeworks it's pointing at. This should resolve these issues.

**Comment by lakmalniranga** [comment]
@HalfdanJ 
Hi,
Can you explain little bit. I have same issue. There's no file called "common-functions.gradle" in "libs/openFrameworksCompiled/project/android"

**Comment by AmineI** [comment]
@lakmalniranga Can you give me the exact path of your gmojiandroid folder ? The "issue" is all about relative paths. It needs to be exactly 3 levels under your ofroot (using the PR files). No more, no less. With the current master branch it must be 4 levels under the ofroot.

**Comment by AmineI** [comment]
example : C:\ofroot\apps\devApps\gmojiAndroid . This works. (Using the mentioned PR files, ofroot and libs;)
(Well, not exactly because I'm on Windows and the relative path is returning anti-slashes at a point (While including add-ons), and it cause an error because \ is the escape character in Java, but that's another story I need to figure out.)

**Comment by lakmalniranga** [comment]
@AmineI That was fixed (i used this https://github.com/HalfdanJ/openFrameworks instead of official repo )
But still got another error. can anyone provide the APK. I'm tried this more than two days :( no luck

 ```
Where:
Build file '/home/owlx/Desktop/of/openFrameworks/libs/openFrameworksCompiled/project/android/build.gradle' line: 157

* What went wrong:
A problem occurred evaluating project ':openFrameworksProject'.
> make failed with exit status 2
```

**Comment by Guiladg** [comment]
Hi @stewdio @alexanderchen @trippedout @HalfdanJ, I have the same issue above. I can't build it because there is no file called "common-functions.gradle" anywhere. Please help me with that, I will really appreciate it. Thanks.

**Comment by axelrindle** [comment]
I fixed it by checking out the [gradle-experiment](https://github.com/halfdanj/openframeworks/tree/gradle-experimental) branch with Git, The file exists in this branch, [as seen here](https://github.com/HalfdanJ/openFrameworks/tree/gradle-experimental/libs/openFrameworksCompiled/project/android).
