### ISSUE TITLE
Error:Execution failed for task ':openFrameworksProject:compileOpenFrameworksLibArmeabi-v7aDebugArm7StaticLibraryOpenFrameworksLibMainCpp'.

### ISSUE THREAD

**Issue by goyalhonney** [googlecreativelab/giantemoji#7]
Error:Execution failed for task ':openFrameworksProject:compileOpenFrameworksLibArmeabi-v7aDebugArm7StaticLibraryOpenFrameworksLibMainCpp'.

Multiple build operations failed.
C++ compiler failed while compiling ofPixels.cpp.
C++ compiler failed while compiling ofRendererCollection.cpp.
C++ compiler failed while compiling of3dGraphics.cpp.
C++ compiler failed while compiling ofTrueTypeFont.cpp.
C++ compiler failed while compiling ofTessellator.cpp.
C++ compiler failed while compiling ofPolyline.cpp.
C++ compiler failed while compiling ofBitmapFont.cpp.
C++ compiler failed while compiling ofImage.cpp.
C++ compiler failed while compiling ofPath.cpp.
C++ compiler failed while compiling ofNode.cpp.
...and 60 more failures.
/openFrameworks/libs/openFrameworksCompiled/project/android/build/tmp/compileOpenFrameworksLibArmeabi-v7aDebugArm7StaticLibraryOpenFrameworksLibMainCpp/output.txt

**Comment by agentmilindu** [comment]
I too get a similar error. Anyway to resolve this?

**Comment by lakmalniranga** [comment]
Same error. How to resolve?

**Comment by Victoryczz** [comment]
Is there anyone can solve this problem? I met this 
Linker failed while linking libOFAndroidApp.so;

it's almost same to the problem;

**Comment by whyameye** [comment]
why is this issue closed with no solution posted? I've having this problem now. Popped up out of nowhere after many successful builds. Looking deeper I see the error is `clang++: error: no such file or directory openFrameworks/libs/openFrameworksCompiled/project/android/build/intermediates/binaries/debug/arm7/obj/armeabi-v7a/libopenFrameworksLib.a` There's no libopenFrameworksLib.a present anywhere on my system. This is supposed to be an Android build.
